"""Migracion Inicial

Revision ID: 940d2d563373
Revises: 
Create Date: 2025-05-06 18:56:16.021486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940d2d563373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fail_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('aq', sa.Integer(), nullable=False),
    sa.Column('uss', sa.Integer(), nullable=False),
    sa.Column('voc', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('fail', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fail_machine')
    # ### end Alembic commands ###
